version: '3.4'


services:
  rabbitmq-ting-tuffer:
    container_name: ting-tuffer-rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest        
    image: rabbitmq:3-management
    networks:
      - ting-tuffer-network

  examples-api-ting-tuffer:
    image: examples-api-ting-tuffer
    container_name: examples-api-ting-tuffer
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
    ports:
      - "80"
      - "8090:443"
    build:
      context: .
      dockerfile: ./Dockerfile.Examples.Api
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks: 
      - ting-tuffer-network
    restart: always
    depends_on:
      - rabbitmq-ting-tuffer

  locust-master:
    image: locustio/locust
    container_name: locust-master
    ports:
     - "8089:8089"
    volumes:
      - ./TingTuffer.Tests.LoadTest/:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H https://examples-api-ting-tuffer/
    networks: 
      - ting-tuffer-network
  
  locust-worker:
    image: locustio/locust
    volumes:
      - ./TingTuffer.Tests.LoadTest/:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host locust-master
    networks: 
      - ting-tuffer-network

networks: 
  ting-tuffer-network:
    driver: bridge