version: '3.4'


services:
  ring-buffer-rabbitmq:
    container_name: ring-buffer-rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest        
    image: rabbitmq:3-management
    networks:
      - ring-buffer-network

  examples-api:
    image: examples-api
    container_name: examples-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "8090:443"
    build:
      context: .
      dockerfile: ./Dockerfile.Examples.Api
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks: 
      - ring-buffer-network
    restart: always
    depends_on:
      - ring-buffer-rabbitmq

  master:
    image: locustio/locust
    container_name: main-locust-ring-buffer
    ports:
     - "8089:8089"
    volumes:
      - ./RingBuffer.Tests.LoadTest/:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H https://examples-api/
    networks: 
      - ring-buffer-network
  
  worker:
    image: locustio/locust
    volumes:
      - ./RingBuffer.Tests.LoadTest/:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
    networks: 
      - ring-buffer-network

networks: 
  ring-buffer-network:
    driver: bridge