name: Publish package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish Nuget Package
      working-directory: ./RingBuffer/bin/Release/
      run:  dotnet nuget push ./RingBuffer.*.nupkg -k ${{ secrets.TOKEN_NUGET }} -s https://nuget.pkg.github.com/teichx/index.json --skip-duplicate
